DROP TABLE IF EXISTS employee;

DROP TABLE IF EXISTS address;

CREATE TABLE employee (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  date_of_birth timestamp NOT NULL,
);

CREATE TABLE address (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  employeeId INT  NOT NULL ,
  line1 VARCHAR(250) NOT NULL,
  line2 VARCHAR(250) NOT NULL,
  city VARCHAR(250) NOT NULL,
  state VARCHAR(250) NOT NULL,
  country VARCHAR(250) NOT NULL,
  zip_code VARCHAR(250) NOT NULL,
);
